const JWT_SECRET=process.env.JWT_SECRET
const SALT_ROUNS=process.env.SALT_ROUNS
const JWT_EXPIRATION_TIME=process.env.JWT_EXPIRATION_TIME
const DATABASE_URL=process.env.DATABASE_URL

export {
  SALT_ROUNS,
  JWT_SECRET,
  JWT_EXPIRATION_TIME,
  DATABASE_URL
}